OANDA_ACCESS_TOKEN = 'f7eff581944bb0b5efb4cac08003be9d-feea72696d43fb03101ddaa84eea2148'
OANDA_ACCOUNT_ID = '101-004-1683826-005'
#symbols for scan
SYMBOLS=[
    'AUD_CAD', 'AUD_CHF', 'AUD_HKD', 'AUD_JPY', 'AUD_NZD', 'AUD_SGD',
    'AUD_USD', 'BCO_USD', 'CAD_CHF', 'CAD_HKD', 'CAD_JPY', 'CAD_SGD',
    'CHF_HKD', 'CHF_JPY', 'CHF_ZAR', 'EUR_AUD', 'EUR_CAD', 'EUR_CHF',
    'EUR_CZK', 'EUR_DKK', 'EUR_GBP', 'EUR_HKD', 'EUR_HUF', 'EUR_JPY',
    'EUR_NOK', 'EUR_NZD', 'EUR_PLN', 'EUR_SEK', 'EUR_SGD', 'EUR_TRY',
    'EUR_USD', 'EUR_ZAR', 'GBP_AUD', 'GBP_CAD', 'GBP_CHF', 'GBP_HKD',
    'GBP_JPY', 'GBP_NZD', 'GBP_PLN', 'GBP_SGD', 'GBP_USD', 'GBP_ZAR',
    'HKD_JPY', 'NZD_CAD', 'NZD_CHF', 'NZD_HKD', 'NZD_JPY', 'NZD_SGD',
    'NZD_USD', 'SGD_CHF', 'SGD_HKD', 'SGD_JPY',
    'USD_CNH', 'USD_CZK', 'USD_DKK', 'USD_HKD', 'USD_HUF', 'USD_INR',
    'USD_JPY', 'USD_MXN', 'USD_NOK', 'USD_PLN', 'USD_SAR', 'USD_SEK',
    'USD_SGD', 'USD_THB', 'USD_TRY', 'USD_ZAR','XAU_USD','ZAR_JPY'
]

SYMBOLS_IGAPI=[
    'AUDCAD', 'AUDCHF', 'AUDHKD', 'AUDJPY', 'AUDNZD', 'AUDSGD',
    'AUDUSD', 'BCOUSD', 'CADCHF', 'CADHKD', 'CADJPY', 'CADSGD',
    'CHFHKD', 'CHFJPY', 'CHFZAR', 'EURAUD', 'EURCAD', 'EURCHF',
    'EURCZK', 'EURDKK', 'EURGBP', 'EURHKD', 'EURHUF', 'EURJPY',
    'EURNOK', 'EURNZD', 'EURPLN', 'EURSEK', 'EURSGD', 'EURTRY',
    'EURUSD', 'EURZAR', 'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPHKD',
    'GBPJPY', 'GBPNZD', 'GBPPLN', 'GBPSGD', 'GBPUSD', 'GBPZAR',
    'HKDJPY', 'NZDCAD', 'NZDCHF', 'NZDHKD', 'NZDJPY', 'NZDSGD',
    'NZDUSD', 'SGDCHF', 'SGDHKD', 'SGDJPY',
    'USDCNH', 'USDCZK', 'USDDKK', 'USDHKD', 'USDHUF', 'USDINR',
    'USDJPY', 'USDMXN', 'USDNOK', 'USDPLN', 'USDSAR', 'USDSEK',
    'USDSGD', 'USDTHB', 'USDTRY', 'USDZAR','XAUUSD','ZARJPY'
]


IG_SERVICE_USERNAME = "TRAIDR1"
IG_SERVICE_PASSWORD = "Melody123"
IG_SERVICE_API_KEY = "36d1c0f25b00ee6340a37fef60791a1f50078e6d"
IG_SERVICE_ACC_TYPE = "LIVE"
IG_SERVICE_ACC_NUMBER = "GVD6L"